### ISSUE TITLE
Service tags not exposed to consul templates

### ISSUE THREAD

**Issue by donniev** [joyent/containerbuddy#54] opened 2015-12-21 18:07 UTC
When I add a tag to a service I cannot access it in a consul template

hexo.json
```
{
  "consul": "consul:8500",
  "onStart": "/opt/containerbuddy/reload-hexo.sh",
  "services": [
    {
      "name": "hexo",
      "port": 4000,
      "tags":["joyent.blog.vawter.com"],
      "health": "/usr/bin/curl --fail -s http://localhost:4000/",
      "poll": 10,
      "ttl": 25
    }
  ],
  "backends": [
      ]
}
```
template
```
{{range services}}
  {{range service .Name}}
    {{.Name}}
    {{.Address}}
    {{.Port}}
    {{.Tags}}
   {{end}}
 {{end}}
```

template output
```
 
    hexo
    192.168.128.235
    4000
    []
```

**Comment by justenwalker** [comment] 2015-12-21 18:38
I think #10 is suppose to add tag support. Right now, Containerbuddy only registers the name, ip, and port number with consul.

**Comment by tgross** [comment] 2015-12-28 13:32
I'm going to close this as a duplicate of https://github.com/joyent/containerbuddy/issues/10, but thanks for the report @donniev

**Closed by tgross** 2015-12-28 13:32 UTC
