### ISSUE TITLE
Race between onStart and starting the main process

### ISSUE THREAD

**Issue by lguminski** [joyent/containerbuddy#110] opened 2016-03-17 15:46 UTC
I have something that looks like a race between `onStart` and the main application process

The main process of container is
```bash
/bin/containerbuddy -config file:///etc/containerbuddy/containerbuddy.json nginx -g "daemon off;"
```
The onStart procedure is
```javascript
"onStart": [
  "consul-template", "-once", "-consul", "localhost:8500", "-template",
  "/etc/containerbuddy/nginx.conf.ctmpl:/etc/nginx/nginx.conf:nginx -s reload"
],
```
The main process sometimes fails to start wit the following error:

    nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory)
    2016/03/16 13:41:41 [ERR] (runner) error running command: exit status 1
    Consul Template returned errors:
    1 error(s) occurred:

    * exit status 12016/03/16 13:41:41 exit status 14

I have strace'd the containerBuddy process (`strace -fF`) and it seems that the execution of `consul-template` against a local cCnsul server is so fast, that sometimes `nginx -s reload` gets executed before `nginx -g "daemon off;"` manages to create the `/var/run/nginx.pid` file.

When it fails the sequence is like this ([strace_bad.txt](https://github.com/joyent/containerbuddy/files/178157/strace_bad.txt))
```
$ grep -nH -e reload -e off -e nginx.pid strace_bad.txt 
strace_bad.txt:1:execve("/bin/containerbuddy", ["/bin/containerbuddy", "-config", "file:///etc/containerbuddy/conta"..., "nginx", "-g", "daemon off;"], [/* 7 vars */]) = 0
strace_bad.txt:2322:[pid    26] execve("/bin/sh", ["/bin/sh", "-c", "nginx -s reload"], [/* 10 vars */] <unfinished ...>
strace_bad.txt:2435:[pid    27] execve("/usr/sbin/nginx", ["nginx", "-s", "reload"], [/* 10 vars */] <unfinished ...>
strace_bad.txt:2831:[pid    27] open("/var/run/nginx.pid", O_RDONLY) = -1 ENOENT (No such file or directory)
strace_bad.txt:2833:[pid    27] write(2, "nginx: [error] open() \"/var/run/"..., 81nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory) 
```
When it works the sequence is different ([strace_good.txt](https://github.com/joyent/containerbuddy/files/178156/strace_good.txt))
```
$ grep -nH -e reload -e off -e nginx.pid strace_good.txt 
strace_good.txt:1:execve("/bin/containerbuddy", ["/bin/containerbuddy", "-config", "file:///etc/containerbuddy/conta"..., "nginx", "-g", "daemon off;"], [/* 7 vars */]) = 0
strace_good.txt:2274:[pid    43] execve("/usr/sbin/nginx", ["nginx", "-g", "daemon off;"], [/* 7 vars */] <unfinished ...>
strace_good.txt:2586:[pid    43] open("/var/run/nginx.pid", O_RDWR|O_CREAT|O_TRUNC, 0644) = 7
```

**Comment by lguminski** [comment] 2016-03-17 15:55
Sources of the project are at https://github.com/ContainerSolutions/workshop-autopilot/releases/tag/cb_raceissue

**Comment by tgross** [comment] 2016-03-17 16:28
@lguminski the expected behavior of the `onStart` handler is to return its exit code before we start the main application. In the `onStart` handler (but not the `onChange` handler) we should remove the `nginx -s reload` so that it reads as follows:

```json
"onStart": [
  "consul-template", "-once", "-consul", "localhost:8500", "-template",
  "/etc/containerbuddy/nginx.conf.ctmpl:/etc/nginx/nginx.conf"
],
```

I'm going to close this issue as it isn't a Containerbuddy defect and open an issue against https://github.com/tgross/workshop-autopilot where the problem seems to be. (ref https://github.com/tgross/workshop-autopilot/blob/containersummit-nyc2016/nginx/containerbuddy.json#L5)

**Closed by tgross** 2016-03-17 16:28 UTC

**Comment by lguminski** [comment] 2016-03-17 16:49
I agree. It is about workshop-autopilot
