### ISSUE TITLE
Add Integration Tests to TravisCI

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerbuddy#42] opened 2015-12-11 15:02 UTC
Bugs like #40 may be difficult to find if we are not exercising more complicated code paths.
Need to add some scripts to test critical paths for a running instance of Containerbuddy. 

We should be able to compose a set of docker containers which can exercise code paths that are important from outside the codebase.

**Comment by justenwalker** [comment] 2015-12-30 21:06
Would it be useful to have some kind of diagnostic interface the Containerbuddy can optionally expose to query its internal state?

IE: we could create a quick TCP endpoint if Containerbuddy is started with a --debug flag - it would accept a simple sequence of bytes like "stat" and then dumps its state in JSON. Inspired by how [Zookeeper](https://zookeeper.apache.org/doc/trunk/zookeeperAdmin.html#The+Four+Letter+Words) implements it.

 Begs the question: should we be querying internal state for integration testing? Or should we only care about the externally visible consequences (IE, We only check the Consul API)

**Comment by tgross** [comment] 2016-01-04 13:06
> Would it be useful to have some kind of diagnostic interface that Containerbuddy can optionally expose to query its internal state?

By design the system is mostly stateless except for the `Config` struct (and its children). State is stored in the discovery service. So although this is a neat idea, I'm not sure if this is all that useful.

> Begs the question: should we be querying internal state for integration testing? Or should we only care about the externally visible state (i.e.: We only check the Consul API)

I think for integration testing we're only going to care about externally visible state.

**Comment by tgross** [comment] 2016-01-05 15:12
Noting this will be a blocker for 1.0.

**Comment by justenwalker** [comment] 2016-01-05 18:02
## Test Harness Framework Proposal 

My goal is to make it somewhat easy to create new integration tests by factoring
out the common logic into a simple framework. 

It might be overkill though, maybe there is an easier way to do it.

### Folder Structure
- `integration_tests/fixtures` - Contains folder for each test harness
- `integration_tests/tests`  - Contains folders for each integration test

#### Fixtures

`integration_tests/fixtures/fixture_name` - Folder contains a `Dockerfile` 
for building a conatainerbuddy app - resulting in an image named `fixture_name`

The `Dockerfile` should specify an ENTRYPOINT/CMD and should not require any arguments.

#### Tests

`integration_tests/tests/test_name` - Contains a `test.sh` script. 
If test.sh returns success: `0` then the test passed, otherwise it failed

This script can make some assumptions:

- `containerbuddy_etcd` and `containerbuddy_consul` are running and are fresh (no data)
- all fixtures in `integration_tests/fixtures` are created and are available as images - requiring no arguments

## Test Running

A script in the top-level folder named `test.sh` which will:

### 1. Re-build, run unit tests, and build Containerbuddy
- `make clean lint build test`

### 2. Setup Test Fixtures
- Scan through all folders in `integration_tests/fixtures` in alpha order
- For each fixture:
  - Copy `build` into `integration_test/fixtures/fixture_name/build` so it can easily be sourced by the `Dockerfile`
  - `cd integration_test/fixtures/fixture_name`
  - `docker build -t fixture_name .`
  - Remove `build` folder to clean up (should add to .gitignore also)

*Note*: Since fixtures are created in alpha order, they can have FROM directives for previously
created images - so as to reduce duplication.

### 3. Run tests
- Scan through all folders in `integration_tests/tests` in alpha order
- For each test:
  - Re-run `containerbuddy_etcd` and `containterbuddy_consul`
  - Run `integration_test/tests/test_name/test.sh`

**Comment by justenwalker** [comment] 2016-01-05 18:23
Added a proposal for discussion in  #67

**Comment by tgross** [comment] 2016-01-14 13:09
Merged with https://github.com/joyent/containerbuddy/pull/72 and awaiting 1.0.

**Comment by tgross** [comment] 2016-01-22 15:23
Released in RC: https://github.com/joyent/containerbuddy/releases/tag/0.1.1

**Closed by tgross** 2016-01-22 15:23 UTC
Labels: enhancement
